title: POTLACH
gems:
  - jekyll-coffeescript
  - jekyll-github-metadata
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
